name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install pyinstaller
    - run: pyinstaller --onefile --windowed --name="PaperWorkflow" Paper_Workflow.py
    - uses: actions/upload-artifact@v4
      with:
        name: PaperWorkflow-EXE
        path: dist/PaperWorkflow.exe
